import json

def convert_json_to_netscape(json_file, txt_file):
    with open(json_file, 'r') as f:
        cookies = json.load(f)
        
    with open(txt_file, 'w') as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# This file is generated by Obsidian AI Brain Engine.\n")
        f.write("# http://curl.haxx.se/rfc/cookie_spec.html\n")
        f.write("# This is a generated file!  Do not edit.\n\n")
        
        for cookie in cookies:
            domain = cookie.get('domain', '')
            include_subdomains = 'TRUE' if domain.startswith('.') else 'FALSE'
            path = cookie.get('path', '/')
            secure = 'TRUE' if cookie.get('secure', False) else 'FALSE'
            
            # expirationDate could be missing for session cookies
            expiration = int(cookie.get('expirationDate', 0))
            
            name = cookie.get('name', '')
            value = cookie.get('value', '')
            
            # Write line
            line = f"{domain}\t{include_subdomains}\t{path}\t{secure}\t{expiration}\t{name}\t{value}\n"
            f.write(line)

if __name__ == "__main__":
    convert_json_to_netscape("cookies.json", "cookies.txt")
