import os
import re
import click
import logging
import subprocess
from datetime import datetime
from google import genai
from google.genai import types
import git

from config import GEMINI_API_KEY, PROJECTS_DIR, OBSIDIAN_BASE_PATH

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)

client = genai.Client(api_key=GEMINI_API_KEY)

def extract_code_blocks(text: str) -> dict:
    """Parses the LLM output to extract main.py and test_main.py."""
    files = {}
    
    # Try to find blocks separated by headers
    main_match = re.search(r'===MAIN\.PY===\n(.*?)(?:===TEST_MAIN\.PY===|\Z)', text, re.DOTALL)
    if main_match:
        code = main_match.group(1).strip()
        code = re.sub(r'^```python\n|```\n?$', '', code).strip() # Clean markdown code blocks
        files['main.py'] = code
        
    test_match = re.search(r'===TEST_MAIN\.PY===\n(.*?)\Z', text, re.DOTALL)
    if test_match:
        code = test_match.group(1).strip()
        code = re.sub(r'^```python\n|```\n?$', '', code).strip()
        files['test_main.py'] = code
        
    return files

def generate_initial_code(spec_content: str) -> dict:
    prompt = f"""You are an elite Python developer practicing Test-Driven Development (TDD) and Spec-Driven Development (SDD).
Here is the project specification generated by our architect:

{spec_content}

Please generate the initial code skeleton for this project.
Write a `main.py` containing the core logic (functions/classes) and a `test_main.py` containing `pytest` cases that test the core logic.
Make sure the code is syntactically correct and the tests actually run against the code in `main.py`.

You MUST output your response EXACTLY in this format:
===MAIN.PY===
[your main.py python code here]

===TEST_MAIN.PY===
import pytest
from main import *
[your test_main.py python code here]
"""
    click.secho("🧠 Requesting initial code generation from Gemini Pro...", fg="cyan")
    response = client.models.generate_content(
        model='gemini-3.5-pro',
        contents=prompt,
        config=types.GenerateContentConfig(temperature=0.2)
    )
    return extract_code_blocks(response.text)

def fix_code(spec_content: str, current_files: dict, error_log: str) -> dict:
    prompt = f"""You are an elite Python developer. The test suite failed.
Project Specification:
{spec_content}

Current main.py:
```python
{current_files.get('main.py', '')}
```

Current test_main.py:
```python
{current_files.get('test_main.py', '')}
```

Pytest Error Log:
{error_log}

Analyze the error and fix either `main.py` or `test_main.py` (or both) so the tests pass.
Output BOTH files again in the exact same format:
===MAIN.PY===
[fixed main.py]

===TEST_MAIN.PY===
[fixed test_main.py]
"""
    click.secho("🛠️ Tests failed. Requesting bug fix from Gemini Pro...", fg="magenta")
    response = client.models.generate_content(
        model='gemini-3.5-pro',
        contents=prompt,
        config=types.GenerateContentConfig(temperature=0.2)
    )
    return extract_code_blocks(response.text)

def run_sdd_on_file(filepath: str) -> bool:
    if not os.path.exists(filepath):
        logger.error(f"File not found: {filepath}")
        return False
        
    with open(filepath, "r", encoding="utf-8") as f:
        spec_content = f.read()
        
    filename = os.path.basename(filepath)
    project_name = re.sub(r'[^a-zA-Z0-9_\u4e00-\u9fa5]', '_', filename.replace('.md', ''))
    
    sandbox_dir = os.path.join(PROJECTS_DIR, "Sandboxes", project_name)
    os.makedirs(sandbox_dir, exist_ok=True)
    logger.info(f"🚀 Initializing SDD loop in sandbox: {sandbox_dir}")
    
    # 1. Generate Code
    files = generate_initial_code(spec_content)
    if not files.get('main.py') or not files.get('test_main.py'):
        logger.error("Failed to parse code from LLM output.")
        return False
        
    main_path = os.path.join(sandbox_dir, "main.py")
    test_path = os.path.join(sandbox_dir, "test_main.py")
    
    max_retries = 3
    passed = False
    
    for attempt in range(max_retries + 1):
        # Write files
        with open(main_path, "w", encoding="utf-8") as f:
            f.write(files['main.py'])
        with open(test_path, "w", encoding="utf-8") as f:
            f.write(files['test_main.py'])
            
        logger.info(f"🔄 [Attempt {attempt+1}] Running pytest...")
        
        # Run pytest
        result = subprocess.run(["pytest", test_path, "-v"], capture_output=True, text=True, cwd=sandbox_dir)
        
        if result.returncode == 0:
            logger.info("✅ All tests passed!")
            passed = True
            break
        else:
            logger.warning("❌ Tests failed.")
            if attempt < max_retries:
                files = fix_code(spec_content, files, result.stdout + "\n" + result.stderr)
            else:
                logger.error("Maximum retries reached.")
                print(result.stdout)
                
    if passed:
        # Commit to Git
        try:
            repo = git.Repo(os.getcwd()) # Assuming ran from root of ObsidianOrganizer
            repo.index.add([main_path, test_path])
            commit_msg = f"feat(sdd): auto-generate passing code for {project_name}"
            repo.index.commit(commit_msg)
            logger.info(f"📦 Successfully committed to git: {commit_msg}")
        except Exception as e:
            logger.warning(f"⚠️ Could not commit to git automatically: {e}")
            
    return passed

def auto_process_pending_specs():
    """Scans the Projects directory for specs tagged with #SDD_Pending and processes them."""
    if not os.path.isdir(PROJECTS_DIR):
        return

    logger.info("🔍 Scanning for #SDD_Pending projects...")
    for filename in os.listdir(PROJECTS_DIR):
        if not filename.endswith(".md"):
            continue
            
        filepath = os.path.join(PROJECTS_DIR, filename)
        try:
            with open(filepath, "r", encoding="utf-8") as f:
                content = f.read()
                
            if "#SDD_Pending" in content:
                logger.info(f"⚡ Found pending SDD project: {filename}")
                success = run_sdd_on_file(filepath)
                
                # Update tag
                if success:
                    content = content.replace("#SDD_Pending", "#SDD_Completed")
                else:
                    content = content.replace("#SDD_Pending", "#SDD_Failed")
                    
                with open(filepath, "w", encoding="utf-8") as f:
                    f.write(content)
                    f.flush()
                    os.fsync(f.fileno())
                    
        except Exception as e:
            logger.error(f"Failed to auto-process {filename}: {e}")

@click.group()
def cli():
    """Obsidian SDD Agent: Converts Spec to Code"""
    pass

@cli.command()
@click.argument('filepath')
def run(filepath):
    """Run SDD Loop on a Markdown Spec file"""
    run_sdd_on_file(filepath)
    
@cli.command()
def auto():
    """Automatically process all pending SDD specs in the Projects directory"""
    auto_process_pending_specs()

if __name__ == "__main__":
    cli()
